#!/bin/sh
# Generated by Codex CLI 0.144.4 (GPT-5).

set -eu

if [ "$#" -ne 2 ]; then
    echo "usage: $0 BUILD_DIR VERSION" >&2
    exit 2
fi

build_dir=$1
version=$2

case "$build_dir" in
    /*) ;;
    *) build_dir=$(pwd)/$build_dir ;;
esac

if [ "$build_dir" = / ]; then
    echo "refusing to use the filesystem root as the build directory" >&2
    exit 2
fi

archive="$build_dir/SDL3_ttf-$version.tar.gz"
source_dir="$build_dir/source"
cmake_dir="$build_dir/cmake"
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

case "$version" in
3.2.2)
    checksum=63547d58d0185c833213885b635a2c0548201cc8f301e6587c0be1a67e1e045d
    ;;
*)
    echo "unsupported SDL3_ttf version: $version" >&2
    exit 2
    ;;
esac

mkdir -p "$build_dir"

if [ ! -f "$archive" ]; then
    curl --fail --location --output "$archive" \
        "https://github.com/libsdl-org/SDL_ttf/releases/download/release-$version/SDL3_ttf-$version.tar.gz"
fi

printf '%s  %s\n' "$checksum" "$archive" | sha256sum --check --status

if [ ! -f "$source_dir/CMakeLists.txt" ]; then
    rm -rf "$source_dir"
    mkdir -p "$source_dir"
    tar -xzf "$archive" --strip-components=1 -C "$source_dir"
fi

embuilder build freetype sdl3
em_cache=$(em-config CACHE)

emcmake cmake \
    -S "$script_dir/SDL3_ttf" \
    -B "$cmake_dir" \
    -DSDL3_TTF_SOURCE_DIR="$source_dir" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS="-sUSE_SDL=3 -sUSE_FREETYPE=1" \
    -DCMAKE_EXE_LINKER_FLAGS="-sUSE_SDL=3 -sUSE_FREETYPE=1" \
    -DFREETYPE_LIBRARY_RELEASE="$em_cache/sysroot/lib/wasm32-emscripten/libfreetype.a" \
    -DFREETYPE_INCLUDE_DIR_ft2build="$em_cache/sysroot/include/freetype2" \
    -DFREETYPE_INCLUDE_DIR_freetype2="$em_cache/sysroot/include/freetype2"

cmake --build "$cmake_dir" --target SDL3_ttf-static
